title: Arrow Inject
#-------------------------
name: Λrrow Inject
#-------------------------
description: Dependency injection for Kotlin Context Receivers
#-------------------------
author: The Λrrow Authors
keywords: functional-programming, kotlin-library, di, dependency injection, context receivers
#-------------------------
url: https://arrow-kt.io/docs/inject
#-------------------------
arrow_url: https://arrow-kt.io
#-------------------------
github_repo: https://github.com/arrow-kt/arrow-inject
#-------------------------
twitter_handle: "@arrow_kt"
#-------------------------
slack_kotlin_channel: "https://slack.kotlinlang.org"
slack_arrow_channel: "https://kotlinlang.slack.com/archives/C5UPMM0A0"
#-------------------------
markdown: kramdown
sass:
    style: compressed
#-------------------------
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile', 'build', 'build.gradle.kts', 'gradle.properties']
#-------------------------
defaults:
  - scope:
      path: "apidocs"
      type: "pages"
    values:
      layout: "docs-inject"
