

package arrow.inject.compiler.plugin.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link arrow.inject.compiler.plugin.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("src/testData/box/context-receivers")
@TestDataPath("$PROJECT_ROOT")
public class BoxTestGenerated extends AbstractBoxTest {
    @Test
    @TestMetadata("a_polymorphic_provider_may_have_injection_arguments_which_are_polymorphically_resolved.kt")
    public void testA_polymorphic_provider_may_have_injection_arguments_which_are_polymorphically_resolved() throws Exception {
        runTest("src/testData/box/context-receivers/a_polymorphic_provider_may_have_injection_arguments_which_are_polymorphically_resolved.kt");
    }

    @Test
    public void testAllFilesPresentInContext_receivers() throws Exception {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/testData/box/context-receivers"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
    }

    @Test
    @TestMetadata("context_receivers.kt")
    public void testContext_receivers() throws Exception {
        runTest("src/testData/box/context-receivers/context_receivers.kt");
    }

    @Test
    @TestMetadata("context_receivers_with_more_than_two_type_parameters.kt")
    public void testContext_receivers_with_more_than_two_type_parameters() throws Exception {
        runTest("src/testData/box/context-receivers/context_receivers_with_more_than_two_type_parameters.kt");
    }

    @Test
    @TestMetadata("context_receivers_with_two_type_parameters.kt")
    public void testContext_receivers_with_two_type_parameters() throws Exception {
        runTest("src/testData/box/context-receivers/context_receivers_with_two_type_parameters.kt");
    }
}
