

package arrow.inject.compiler.plugin.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link GenerateNewCompilerTests.kt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("src/testData/box/context")
@TestDataPath("$PROJECT_ROOT")
public class BoxTestGenerated extends AbstractBoxTest {
    @Test
    public void testAllFilesPresentInContext() throws Exception {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/testData/box/context"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
    }

    @Test
    @TestMetadata("different_context_providers_of_the_same_type_are_not_ambiguous.kt")
    public void testDifferent_context_providers_of_the_same_type_are_not_ambiguous() throws Exception {
        runTest("src/testData/box/context/different_context_providers_of_the_same_type_are_not_ambiguous.kt");
    }

    @Test
    @TestMetadata("multiple_context_providers_are_supported.kt")
    public void testMultiple_context_providers_are_supported() throws Exception {
        runTest("src/testData/box/context/multiple_context_providers_are_supported.kt");
    }
}
